### ISSUE TITLE
[BUG] ValueError: End must be after begin

### ISSUE THREAD

**Issue by lk2322** [iburakov/my-itmo-ru-to-ical#5]
```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsg
i_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in ful
l_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in ful
l_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dis
patch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 277, in _
_call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in res
ult
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __g
et_result
    raise self._exception
  File "/app/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 353, in m
ain_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/app.py", line 47, in get_calendar
    calendar = build_calendar(lesson_events)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/calendar_processing.py", line 14, in build_calendar
    for event in events:
  File "/app/src/lessons_to_events.py", line 54, in raw_lesson_to_event
    event = Event(
            ^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/ics/event.py", line 115, in __in
it__
    self.end = end
    ^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/ics/event.py", line 195, in end
    raise ValueError('End must be after begin')
ValueError: End must be after begin
```
Looks like something wrong with the calendar building process. I will check this for more info

**Comment by lk2322** [comment]
I think this causes the exception 
![Screenshot_20240406-001015~2](https://github.com/iburakov/my-itmo-ru-to-ical/assets/39478731/2272bcc6-505c-4b60-be39-114641a5cdd7)
